//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_AdditionalInfoofVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAR_AdditionalInfoofVehicle()
        {
            this.FAR_AdditionalInfoofVehicleDetail = new HashSet<FAR_AdditionalInfoofVehicleDetail>();
        }
    
        public int Id { get; set; }
        public int FIxedAssetId { get; set; }
        public Nullable<int> SourceOfFundId { get; set; }
        public string Registration { get; set; }
        public string Chassis { get; set; }
        public string Engine { get; set; }
        public string CC { get; set; }
        public Nullable<int> Seats { get; set; }
        public int ZoneInfoId { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_AdditionalInfoofVehicleDetail> FAR_AdditionalInfoofVehicleDetail { get; set; }
        public virtual FAR_FixedAsset FAR_FixedAsset { get; set; }
    }
}
