//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_FixedAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAR_FixedAsset()
        {
            this.FAR_AccidentInformation = new HashSet<FAR_AccidentInformation>();
            this.FAR_AdditionalInfoofVehicle = new HashSet<FAR_AdditionalInfoofVehicle>();
            this.FAR_AssetTransfer = new HashSet<FAR_AssetTransfer>();
            this.FAR_Repair = new HashSet<FAR_Repair>();
            this.FAR_SaleDisposal = new HashSet<FAR_SaleDisposal>();
            this.FAR_DepreciationDetail = new HashSet<FAR_DepreciationDetail>();
        }
    
        public int Id { get; set; }
        public int ItemTypeId { get; set; }
        public int ZoneInfoId { get; set; }
        public string AssetType { get; set; }
        public bool IsRefurbishment { get; set; }
        public bool IsCalculateDepreciation { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public Nullable<decimal> DepreciationRate { get; set; }
        public int AssetStatusId { get; set; }
        public Nullable<int> AssetConditionId { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime DepreciationEffectiveDate { get; set; }
        public decimal AssetCost { get; set; }
        public Nullable<decimal> OBDepreciation { get; set; }
        public Nullable<decimal> OBBookValue { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> BeneficiaryEmployeeId { get; set; }
        public bool IsAllowDepreciationCal { get; set; }
        public string SerialNo { get; set; }
        public string Remarks { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> OrganogramLevelId { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> ItemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_AccidentInformation> FAR_AccidentInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_AdditionalInfoofVehicle> FAR_AdditionalInfoofVehicle { get; set; }
        public virtual FAR_AssetCondition FAR_AssetCondition { get; set; }
        public virtual FAR_AssetStatus FAR_AssetStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_AssetTransfer> FAR_AssetTransfer { get; set; }
        public virtual FAR_Catagory FAR_Catagory { get; set; }
        public virtual FAR_Location FAR_Location { get; set; }
        public virtual FAR_SubCategory FAR_SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_Repair> FAR_Repair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_SaleDisposal> FAR_SaleDisposal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_DepreciationDetail> FAR_DepreciationDetail { get; set; }
    }
}
