//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_AccidentInformation
    {
        public int Id { get; set; }
        public int FIxedAssetId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Driver { get; set; }
        public string Description { get; set; }
        public int ZoneInfoId { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual FAR_FixedAsset FAR_FixedAsset { get; set; }
    }
}
