//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_DepreciationDetail
    {
        public int Id { get; set; }
        public int DepreciationId { get; set; }
        public int FixedAssetId { get; set; }
        public int AssetStatusId { get; set; }
        public int AssetConditionId { get; set; }
        public decimal DepreciationRate { get; set; }
        public decimal AssetCost { get; set; }
        public decimal OBBookValue { get; set; }
        public decimal OBDepreciation { get; set; }
        public decimal Depreciation { get; set; }
        public decimal CBDepreciation { get; set; }
        public decimal CBBookValue { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual FAR_AssetCondition FAR_AssetCondition { get; set; }
        public virtual FAR_AssetStatus FAR_AssetStatus { get; set; }
        public virtual FAR_Depreciation FAR_Depreciation { get; set; }
        public virtual FAR_FixedAsset FAR_FixedAsset { get; set; }
    }
}
