//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_AssetMaintenanceInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAR_AssetMaintenanceInformation()
        {
            this.FAR_AssetMaintenanceInformationDetail = new HashSet<FAR_AssetMaintenanceInformationDetail>();
        }
    
        public int Id { get; set; }
        public int FIxedAssetId { get; set; }
        public System.DateTime Date { get; set; }
        public int MaintenanceTypeInfoId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int ZoneInfoId { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string FileName { get; set; }
        public byte[] Attachment { get; set; }
    
        public virtual FAR_MaintenanceTypeInformation FAR_MaintenanceTypeInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_AssetMaintenanceInformationDetail> FAR_AssetMaintenanceInformationDetail { get; set; }
    }
}
