//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_Cost_Centre_or_Institute_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_Cost_Centre_or_Institute_Information()
        {
            this.acc_Cost_Centre_or_Institute_Information1 = new HashSet<acc_Cost_Centre_or_Institute_Information>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public int codeCount { get; set; }
        public string userCode { get; set; }
        public bool isInstitute { get; set; }
        public string name { get; set; }
        public string NameForBankAdviceLetter { get; set; }
        public Nullable<decimal> paAmmount { get; set; }
        public string remarks { get; set; }
        public Nullable<int> parentId { get; set; }
        public int CostCenterTypeId { get; set; }
        public Nullable<int> empId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int entityId { get; set; }
        public Nullable<int> ZoneInfoId { get; set; }
        public Nullable<bool> isBudgetHead { get; set; }
        public Nullable<int> BudgetGroupId { get; set; }
        public Nullable<bool> IsFixedAssetHead { get; set; }
        public Nullable<bool> IsFixedAssetDevWork { get; set; }
        public Nullable<bool> IsFixedAssetNonDevWork { get; set; }
        public Nullable<decimal> DepreciationRate { get; set; }
        public Nullable<System.DateTime> createdUserDate { get; set; }
        public string createdUserId { get; set; }
        public Nullable<System.DateTime> updatedUserDate { get; set; }
        public string updatedUserId { get; set; }
        public string BudgetCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_Cost_Centre_or_Institute_Information> acc_Cost_Centre_or_Institute_Information1 { get; set; }
        public virtual acc_Cost_Centre_or_Institute_Information acc_Cost_Centre_or_Institute_Information2 { get; set; }
    }
}
