//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMS_BankWiseOfferRate
    {
        public int Id { get; set; }
        public int BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> OfferRate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int FDRTypeId { get; set; }
    
        public virtual FMS_BankInfo FMS_BankInfo { get; set; }
        public virtual FMS_BankInfoBranchDetail FMS_BankInfoBranchDetail { get; set; }
        public virtual FMS_FDRType FMS_FDRType { get; set; }
    }
}
