//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMS_CPFInterestReceivable
    {
        public int Id { get; set; }
        public int FixedDepositInfoId { get; set; }
        public int FinancialYearId { get; set; }
        public Nullable<decimal> DistributedAmount { get; set; }
        public Nullable<decimal> ApplicableMonth { get; set; }
        public Nullable<decimal> OtherExciseDuty { get; set; }
        public Nullable<decimal> ApproxInterestDuring { get; set; }
    
        public virtual FMS_FixedDepositInfo FMS_FixedDepositInfo { get; set; }
    }
}
