//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMS_FDRClosingInfo
    {
        public int Id { get; set; }
        public int FixedDepositInfoId { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public decimal FDRAmount { get; set; }
        public decimal InterestRate { get; set; }
        public decimal TaxRate { get; set; }
        public decimal Duration { get; set; }
        public Nullable<int> ProfitRecvId { get; set; }
        public decimal InterestAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal BankCharge { get; set; }
        public decimal ProfitAmount { get; set; }
        public decimal TotalReceivableAmount { get; set; }
        public decimal ClosingAmount { get; set; }
        public decimal LossAmount { get; set; }
        public Nullable<int> ChequeId { get; set; }
        public string Description { get; set; }
        public bool IsRenew { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<decimal> WithdrawalAmount { get; set; }
        public bool IsFDRSaved { get; set; }
    
        public virtual FMS_FixedDepositInfo FMS_FixedDepositInfo { get; set; }
    }
}
