//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_ItemType()
        {
            this.INV_DelegationApprovalInfo = new HashSet<INV_DelegationApprovalInfo>();
            this.INV_ItemInfo = new HashSet<INV_ItemInfo>();
            this.INV_ItemType1 = new HashSet<INV_ItemType>();
        }
    
        public int Id { get; set; }
        public bool IsGroup { get; set; }
        public string Code { get; set; }
        public int CodeCount { get; set; }
        public int Level { get; set; }
        public string ItemTypeName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> BudgetHeadId { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_DelegationApprovalInfo> INV_DelegationApprovalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ItemInfo> INV_ItemInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ItemType> INV_ItemType1 { get; set; }
        public virtual INV_ItemType INV_ItemType2 { get; set; }
    }
}
