//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ItemInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_ItemInfo()
        {
            this.INV_TransferInItem = new HashSet<INV_TransferInItem>();
            this.INV_IssueItem = new HashSet<INV_IssueItem>();
            this.INV_PurchaseItem = new HashSet<INV_PurchaseItem>();
            this.INV_TransferOutItem = new HashSet<INV_TransferOutItem>();
            this.INV_AdjustmentItem = new HashSet<INV_AdjustmentItem>();
            this.INV_IssueReturnItem = new HashSet<INV_IssueReturnItem>();
            this.INV_AssetQuotaInfo = new HashSet<INV_AssetQuotaInfo>();
            this.INV_PeriodicAssetDuration = new HashSet<INV_PeriodicAssetDuration>();
            this.INV_ScrapItem = new HashSet<INV_ScrapItem>();
            this.INV_RequisitionItem = new HashSet<INV_RequisitionItem>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> MinimumQuantity { get; set; }
        public Nullable<int> ReOrderQuantity { get; set; }
        public Nullable<int> MaximumQuantity { get; set; }
        public Nullable<bool> IsPeriodicAsset { get; set; }
        public Nullable<bool> IsCondemnableAsset { get; set; }
        public Nullable<bool> HasQuota { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string Size { get; set; }
        public string Remarks { get; set; }
        public int AssetGroupId { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual INV_Category INV_Category { get; set; }
        public virtual INV_Color INV_Color { get; set; }
        public virtual INV_Manufacturer INV_Manufacturer { get; set; }
        public virtual INV_Model INV_Model { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TransferInItem> INV_TransferInItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_IssueItem> INV_IssueItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PurchaseItem> INV_PurchaseItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TransferOutItem> INV_TransferOutItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_AdjustmentItem> INV_AdjustmentItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_IssueReturnItem> INV_IssueReturnItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_AssetQuotaInfo> INV_AssetQuotaInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PeriodicAssetDuration> INV_PeriodicAssetDuration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ScrapItem> INV_ScrapItem { get; set; }
        public virtual INV_ItemType INV_ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_RequisitionItem> INV_RequisitionItem { get; set; }
    }
}
