//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_IssueInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_IssueInfo()
        {
            this.INV_IssueItem = new HashSet<INV_IssueItem>();
        }
    
        public int Id { get; set; }
        public string IssueNo { get; set; }
        public int IndentId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> IndentDate { get; set; }
        public int IssuedToId { get; set; }
        public int IssuedById { get; set; }
        public string Comment { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int ZoneInfoId { get; set; }
    
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_IssueItem> INV_IssueItem { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo1 { get; set; }
        public virtual INV_RequisitionInfo INV_RequisitionInfo { get; set; }
    }
}
