//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TransferInInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_TransferInInfo()
        {
            this.INV_TransferInItem = new HashSet<INV_TransferInItem>();
        }
    
        public int Id { get; set; }
        public int ZoneInfoId { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string TransferNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string ChallanNo { get; set; }
        public int ReceivedFromId { get; set; }
        public int ReceivedById { get; set; }
        public string Comment { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public byte[] Attachment { get; set; }
        public string FileName { get; set; }
        public Nullable<int> TransferOutId { get; set; }
    
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
        public virtual PRM_ZoneInfo PRM_ZoneInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TransferInItem> INV_TransferInItem { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
        public virtual INV_TransferOutInfo INV_TransferOutInfo { get; set; }
    }
}
