//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_DelegationApprovalInfo
    {
        public int Id { get; set; }
        public int ItemTypeId { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public decimal ApprovalLimit { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int ZoneInfoId { get; set; }
    
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
        public virtual INV_ItemType INV_ItemType { get; set; }
    }
}
