//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_AdjustmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_AdjustmentInfo()
        {
            this.INV_AdjustmentItem = new HashSet<INV_AdjustmentItem>();
        }
    
        public int Id { get; set; }
        public string AdjustmentNo { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
        public int AdjustedByEmpId { get; set; }
        public int ApprovedByEmpId { get; set; }
        public string Comment { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int ZoneInfoId { get; set; }
        public byte[] Attachment { get; set; }
        public string FileName { get; set; }
    
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_AdjustmentItem> INV_AdjustmentItem { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo1 { get; set; }
    }
}
