//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.INV
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINVItemHistory
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public System.DateTime Date { get; set; }
        public string Challan { get; set; }
        public string TransactionType { get; set; }
        public decimal InQuantity { get; set; }
        public decimal OutQuantity { get; set; }
        public int ZoneInfoId { get; set; }
        public System.DateTime IDate { get; set; }
    }
}
