//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.CPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_LoanPolicy
    {
        public int Id { get; set; }
        public string LoanPolicyFor { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> NRfLoanPercentage { get; set; }
        public string NRfApplicableFor { get; set; }
        public Nullable<int> NRfMinimumAge { get; set; }
        public decimal RfLoanPercentage { get; set; }
        public string RfApplicableFor { get; set; }
        public bool IsRfDeductFromBalance { get; set; }
        public bool IsRfInstallmentAddedWithBalance { get; set; }
        public int RfMaxConcurrentLoan { get; set; }
        public int RfMinServiceYear { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    }
}
