//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.CPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_MembershipInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPF_MembershipInfo()
        {
            this.CPF_MemberNominee = new HashSet<CPF_MemberNominee>();
            this.CPF_ProfitDistributionDetail = new HashSet<CPF_ProfitDistributionDetail>();
            this.CPF_OpeningBalance = new HashSet<CPF_OpeningBalance>();
            this.CPF_Settlement = new HashSet<CPF_Settlement>();
            this.CPF_Withdraw = new HashSet<CPF_Withdraw>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string MembershipID { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string WitnessName { get; set; }
        public string WitnessDesignation { get; set; }
        public string WitnessAddress { get; set; }
        public string WitnessMembershipID { get; set; }
        public string Witness2Name { get; set; }
        public string Witness2Designation { get; set; }
        public string Witness2Address { get; set; }
        public string Witness2MembershipID { get; set; }
        public string MembershipStatus { get; set; }
        public int ApprovalStatusId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<int> ApprovalPathId { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string OfficeName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string SectionName { get; set; }
        public string PresentPayScale { get; set; }
        public Nullable<decimal> PresentBasicPay { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<System.DateTime> ApplicationReceiptDate { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime PermanentDate { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPF_MemberNominee> CPF_MemberNominee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPF_ProfitDistributionDetail> CPF_ProfitDistributionDetail { get; set; }
        public virtual APV_ApprovalStatus APV_ApprovalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPF_OpeningBalance> CPF_OpeningBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPF_Settlement> CPF_Settlement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPF_Withdraw> CPF_Withdraw { get; set; }
    }
}
