//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.CPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_Settlement
    {
        public int Id { get; set; }
        public int MembershipId { get; set; }
        public System.DateTime InactiveDate { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public decimal OutgoingProfitRate { get; set; }
        public decimal MembershipLengthInYear { get; set; }
        public string Remarks { get; set; }
        public decimal EmpOpening { get; set; }
        public decimal EmpContributionInPeriod { get; set; }
        public decimal EmpProftInPeriod { get; set; }
        public decimal EmpWithdrawnInPeriod { get; set; }
        public decimal EmpBalance { get; set; }
        public decimal ComOpening { get; set; }
        public decimal ComContributionInPeriod { get; set; }
        public decimal ComProftInPeriod { get; set; }
        public decimal ForfeitedAmount { get; set; }
        public decimal ComBalance { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<int> LoanId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> LoanRefund { get; set; }
        public Nullable<decimal> DueLoan { get; set; }
        public decimal OtherDeduction { get; set; }
        public decimal NetPayable { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int PeriodId { get; set; }
    
        public virtual CPF_MembershipInfo CPF_MembershipInfo { get; set; }
    }
}
