//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.CPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_ForfeitedRule
    {
        public int Id { get; set; }
        public decimal FromServiceLength { get; set; }
        public decimal ToServiceLength { get; set; }
        public decimal ForfeitedRate { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    }
}
