//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.CPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_OpeningBalance
    {
        public int Id { get; set; }
        public int MembershipId { get; set; }
        public System.DateTime DateOfOpening { get; set; }
        public decimal EmpTotal { get; set; }
        public decimal ComTotal { get; set; }
        public decimal EmpCoreContribution { get; set; }
        public decimal EmpProfit { get; set; }
        public decimal ComCoreContribution { get; set; }
        public decimal ComProfit { get; set; }
        public decimal PrevYearEmpCoreContribution { get; set; }
        public decimal PrevYearEmpProfit { get; set; }
        public decimal PrevYearComCoreContribution { get; set; }
        public decimal PrevYearComProfit { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual CPF_MembershipInfo CPF_MembershipInfo { get; set; }
    }
}
