//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.CPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_BEPZACPFEntities : DbContext
    {
        public ERP_BEPZACPFEntities()
            : base("name=ERP_BEPZACPFEntities")
        {
            // Get the ObjectContext related to this DbContext
            var objectContext = (this as IObjectContextAdapter).ObjectContext;

            // Sets the command timeout for all the commands
            objectContext.CommandTimeout = 3600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CPF_AccountHeadCategory> CPF_AccountHeadCategory { get; set; }
        public virtual DbSet<CPF_BankAccountInfo> CPF_BankAccountInfo { get; set; }
        public virtual DbSet<CPF_ContributionRateSetup> CPF_ContributionRateSetup { get; set; }
        public virtual DbSet<CPF_DocumentType> CPF_DocumentType { get; set; }
        public virtual DbSet<CPF_ForfeitedRule> CPF_ForfeitedRule { get; set; }
        public virtual DbSet<CPF_GratuityInterestRate> CPF_GratuityInterestRate { get; set; }
        public virtual DbSet<CPF_LoanPolicy> CPF_LoanPolicy { get; set; }
        public virtual DbSet<CPF_MemberNominee> CPF_MemberNominee { get; set; }
        public virtual DbSet<CPF_PaymentType> CPF_PaymentType { get; set; }
        public virtual DbSet<CPF_ProfitDistributionDetail> CPF_ProfitDistributionDetail { get; set; }
        public virtual DbSet<CPF_SpecialParameter> CPF_SpecialParameter { get; set; }
        public virtual DbSet<CommonConfigType> CommonConfigTypes { get; set; }
        public virtual DbSet<CPF_DefaultMapping> CPF_DefaultMapping { get; set; }
        public virtual DbSet<vwCPFNominee> vwCPFNominees { get; set; }
        public virtual DbSet<CPF_MembershipInfo> CPF_MembershipInfo { get; set; }
        public virtual DbSet<APV_ApprovalStatus> APV_ApprovalStatus { get; set; }
        public virtual DbSet<CustomPropertyAttribute> CustomPropertyAttributes { get; set; }
        public virtual DbSet<CPF_ProfitInterestRate> CPF_ProfitInterestRate { get; set; }
        public virtual DbSet<CPF_OpeningBalance> CPF_OpeningBalance { get; set; }
        public virtual DbSet<CPF_ProfitDistribution> CPF_ProfitDistribution { get; set; }
        public virtual DbSet<CPF_Settlement> CPF_Settlement { get; set; }
        public virtual DbSet<CPF_Withdraw> CPF_Withdraw { get; set; }
    
        public virtual int CommonConfigTypeDML(string strDisplayName, Nullable<int> intID, string strName, Nullable<int> intSortOrder, string strRemarks, string strUser, string strMode, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var strDisplayNameParameter = strDisplayName != null ?
                new ObjectParameter("strDisplayName", strDisplayName) :
                new ObjectParameter("strDisplayName", typeof(string));
    
            var intIDParameter = intID.HasValue ?
                new ObjectParameter("intID", intID) :
                new ObjectParameter("intID", typeof(int));
    
            var strNameParameter = strName != null ?
                new ObjectParameter("strName", strName) :
                new ObjectParameter("strName", typeof(string));
    
            var intSortOrderParameter = intSortOrder.HasValue ?
                new ObjectParameter("intSortOrder", intSortOrder) :
                new ObjectParameter("intSortOrder", typeof(int));
    
            var strRemarksParameter = strRemarks != null ?
                new ObjectParameter("strRemarks", strRemarks) :
                new ObjectParameter("strRemarks", typeof(string));
    
            var strUserParameter = strUser != null ?
                new ObjectParameter("strUser", strUser) :
                new ObjectParameter("strUser", typeof(string));
    
            var strModeParameter = strMode != null ?
                new ObjectParameter("strMode", strMode) :
                new ObjectParameter("strMode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonConfigTypeDML", strDisplayNameParameter, intIDParameter, strNameParameter, intSortOrderParameter, strRemarksParameter, strUserParameter, strModeParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<GetMyLoanStatusResult> CPF_GetMyLoanStatus(Nullable<int> employeeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMyLoanStatusResult>("CPF_GetMyLoanStatus", employeeIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_procGetBalanceScheet(Nullable<int> intPeriodId, Nullable<int> selectedLavel, Nullable<System.DateTime> balanceDate, Nullable<int> isIncludeZero, Nullable<int> isIncludePostingAcc, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var intPeriodIdParameter = intPeriodId.HasValue ?
                new ObjectParameter("intPeriodId", intPeriodId) :
                new ObjectParameter("intPeriodId", typeof(int));
    
            var selectedLavelParameter = selectedLavel.HasValue ?
                new ObjectParameter("SelectedLavel", selectedLavel) :
                new ObjectParameter("SelectedLavel", typeof(int));
    
            var balanceDateParameter = balanceDate.HasValue ?
                new ObjectParameter("BalanceDate", balanceDate) :
                new ObjectParameter("BalanceDate", typeof(System.DateTime));
    
            var isIncludeZeroParameter = isIncludeZero.HasValue ?
                new ObjectParameter("IsIncludeZero", isIncludeZero) :
                new ObjectParameter("IsIncludeZero", typeof(int));
    
            var isIncludePostingAccParameter = isIncludePostingAcc.HasValue ?
                new ObjectParameter("IsIncludePostingAcc", isIncludePostingAcc) :
                new ObjectParameter("IsIncludePostingAcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_procGetBalanceScheet", intPeriodIdParameter, selectedLavelParameter, balanceDateParameter, isIncludeZeroParameter, isIncludePostingAccParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_procGetIncomeExpenditure(Nullable<int> intPeriodId, Nullable<int> selectedLavel, Nullable<System.DateTime> balanceDate, Nullable<int> isIncludeZero, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var intPeriodIdParameter = intPeriodId.HasValue ?
                new ObjectParameter("intPeriodId", intPeriodId) :
                new ObjectParameter("intPeriodId", typeof(int));
    
            var selectedLavelParameter = selectedLavel.HasValue ?
                new ObjectParameter("SelectedLavel", selectedLavel) :
                new ObjectParameter("SelectedLavel", typeof(int));
    
            var balanceDateParameter = balanceDate.HasValue ?
                new ObjectParameter("BalanceDate", balanceDate) :
                new ObjectParameter("BalanceDate", typeof(System.DateTime));
    
            var isIncludeZeroParameter = isIncludeZero.HasValue ?
                new ObjectParameter("IsIncludeZero", isIncludeZero) :
                new ObjectParameter("IsIncludeZero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_procGetIncomeExpenditure", intPeriodIdParameter, selectedLavelParameter, balanceDateParameter, isIncludeZeroParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_procGetTrialBalance(Nullable<int> intPeriodId, Nullable<int> selectedLavel, Nullable<System.DateTime> balanceDate, Nullable<int> isIncludeZero, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var intPeriodIdParameter = intPeriodId.HasValue ?
                new ObjectParameter("intPeriodId", intPeriodId) :
                new ObjectParameter("intPeriodId", typeof(int));
    
            var selectedLavelParameter = selectedLavel.HasValue ?
                new ObjectParameter("SelectedLavel", selectedLavel) :
                new ObjectParameter("SelectedLavel", typeof(int));
    
            var balanceDateParameter = balanceDate.HasValue ?
                new ObjectParameter("BalanceDate", balanceDate) :
                new ObjectParameter("BalanceDate", typeof(System.DateTime));
    
            var isIncludeZeroParameter = isIncludeZero.HasValue ?
                new ObjectParameter("IsIncludeZero", isIncludeZero) :
                new ObjectParameter("IsIncludeZero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_procGetTrialBalance", intPeriodIdParameter, selectedLavelParameter, balanceDateParameter, isIncludeZeroParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_procProfitDistributionRollbackIndividual(Nullable<int> periodId, Nullable<int> detailId, string strUser, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var detailIdParameter = detailId.HasValue ?
                new ObjectParameter("DetailId", detailId) :
                new ObjectParameter("DetailId", typeof(int));
    
            var strUserParameter = strUser != null ?
                new ObjectParameter("strUser", strUser) :
                new ObjectParameter("strUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_procProfitDistributionRollbackIndividual", periodIdParameter, detailIdParameter, strUserParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_AdvanceRefundRealized(string refundType, Nullable<System.DateTime> startPeriod, Nullable<System.DateTime> endPeriod, Nullable<int> divisionId, Nullable<int> gradId, Nullable<int> designationId, Nullable<int> membershipId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var refundTypeParameter = refundType != null ?
                new ObjectParameter("RefundType", refundType) :
                new ObjectParameter("RefundType", typeof(string));
    
            var startPeriodParameter = startPeriod.HasValue ?
                new ObjectParameter("StartPeriod", startPeriod) :
                new ObjectParameter("StartPeriod", typeof(System.DateTime));
    
            var endPeriodParameter = endPeriod.HasValue ?
                new ObjectParameter("EndPeriod", endPeriod) :
                new ObjectParameter("EndPeriod", typeof(System.DateTime));
    
            var divisionIdParameter = divisionId.HasValue ?
                new ObjectParameter("DivisionId", divisionId) :
                new ObjectParameter("DivisionId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var membershipIdParameter = membershipId.HasValue ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_AdvanceRefundRealized", refundTypeParameter, startPeriodParameter, endPeriodParameter, divisionIdParameter, gradIdParameter, designationIdParameter, membershipIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_AvailableInvAccrualStepNo_Result> CPF_AvailableInvAccrualStepNo(Nullable<int> investmentId)
        {
            var investmentIdParameter = investmentId.HasValue ?
                new ObjectParameter("InvestmentId", investmentId) :
                new ObjectParameter("InvestmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_AvailableInvAccrualStepNo_Result>("CPF_AvailableInvAccrualStepNo", investmentIdParameter);
        }
    
        public virtual int CPF_BalanceSheetByLevel(Nullable<int> selectedLavel, Nullable<int> periodId)
        {
            var selectedLavelParameter = selectedLavel.HasValue ?
                new ObjectParameter("SelectedLavel", selectedLavel) :
                new ObjectParameter("SelectedLavel", typeof(int));
    
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_BalanceSheetByLevel", selectedLavelParameter, periodIdParameter);
        }
    
        public virtual int CPF_DeleteApprovalFlowByDocumentID(Nullable<int> documentId, Nullable<int> documentTypeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(int));
    
            var documentTypeIdParameter = documentTypeId.HasValue ?
                new ObjectParameter("DocumentTypeId", documentTypeId) :
                new ObjectParameter("DocumentTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_DeleteApprovalFlowByDocumentID", documentIdParameter, documentTypeIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_EmployeeCPF_WF_FundStatus_Result> CPF_EmployeeCPF_WF_FundStatus(Nullable<int> employeeId, Nullable<System.DateTime> applicationDate)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var applicationDateParameter = applicationDate.HasValue ?
                new ObjectParameter("ApplicationDate", applicationDate) :
                new ObjectParameter("ApplicationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_EmployeeCPF_WF_FundStatus_Result>("CPF_EmployeeCPF_WF_FundStatus", employeeIdParameter, applicationDateParameter);
        }
    
        public virtual ObjectResult<CPF_GetApprovalStatusList_Result> CPF_GetApprovalStatusList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetApprovalStatusList_Result>("CPF_GetApprovalStatusList");
        }
    
        public virtual ObjectResult<CPF_GetChartOfAccount_Result> CPF_GetChartOfAccount(Nullable<bool> isPostingHead, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var isPostingHeadParameter = isPostingHead.HasValue ?
                new ObjectParameter("IsPostingHead", isPostingHead) :
                new ObjectParameter("IsPostingHead", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetChartOfAccount_Result>("CPF_GetChartOfAccount", isPostingHeadParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<GetDebitOrCredit> CPF_GetDebitCreditBankReconciliation(Nullable<int> bankAccountId, string transactionType, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var bankAccountIdParameter = bankAccountId.HasValue ?
                new ObjectParameter("BankAccountId", bankAccountId) :
                new ObjectParameter("BankAccountId", typeof(int));
    
            var transactionTypeParameter = transactionType != null ?
                new ObjectParameter("TransactionType", transactionType) :
                new ObjectParameter("TransactionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDebitOrCredit>("CPF_GetDebitCreditBankReconciliation", bankAccountIdParameter, transactionTypeParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_GetDesignationList_Result> CPF_GetDesignationList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetDesignationList_Result>("CPF_GetDesignationList");
        }
    
        public virtual ObjectResult<CPF_GetDivisionUnit_Result> CPF_GetDivisionUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetDivisionUnit_Result>("CPF_GetDivisionUnit");
        }
    
        public virtual ObjectResult<CPF_GetJobGradeList_Result> CPF_GetJobGradeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetJobGradeList_Result>("CPF_GetJobGradeList");
        }
    
        public virtual ObjectResult<CPF_GetLevelOfCOA_Result> CPF_GetLevelOfCOA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetLevelOfCOA_Result>("CPF_GetLevelOfCOA");
        }
    
        public virtual ObjectResult<CPF_GetLoanPolicy_Result> CPF_GetLoanPolicy(Nullable<System.DateTime> applicationDate, Nullable<bool> isEligibleForCpf)
        {
            var applicationDateParameter = applicationDate.HasValue ?
                new ObjectParameter("ApplicationDate", applicationDate) :
                new ObjectParameter("ApplicationDate", typeof(System.DateTime));
    
            var isEligibleForCpfParameter = isEligibleForCpf.HasValue ?
                new ObjectParameter("IsEligibleForCpf", isEligibleForCpf) :
                new ObjectParameter("IsEligibleForCpf", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetLoanPolicy_Result>("CPF_GetLoanPolicy", applicationDateParameter, isEligibleForCpfParameter);
        }
    
        public virtual ObjectResult<CPF_GetPFYearList_Result> CPF_GetPFYearList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetPFYearList_Result>("CPF_GetPFYearList");
        }
    
        public virtual ObjectResult<CPF_GetTestName_Result> CPF_GetTestName(string initial, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var initialParameter = initial != null ?
                new ObjectParameter("Initial", initial) :
                new ObjectParameter("Initial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetTestName_Result>("CPF_GetTestName", initialParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_GetVoucherTypeList_Result> CPF_GetVoucherTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetVoucherTypeList_Result>("CPF_GetVoucherTypeList");
        }
    
        public virtual int CPF_IncomeExpenceStatementByLevel(Nullable<int> selectedLavel, Nullable<int> periodId)
        {
            var selectedLavelParameter = selectedLavel.HasValue ?
                new ObjectParameter("SelectedLavel", selectedLavel) :
                new ObjectParameter("SelectedLavel", typeof(int));
    
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_IncomeExpenceStatementByLevel", selectedLavelParameter, periodIdParameter);
        }
    
        public virtual ObjectResult<CPF_MemberSchedule_Result> CPF_MemberSchedule(Nullable<int> periodId, Nullable<int> divisionId, Nullable<int> gradId, Nullable<int> designationId, Nullable<int> membershipId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var divisionIdParameter = divisionId.HasValue ?
                new ObjectParameter("DivisionId", divisionId) :
                new ObjectParameter("DivisionId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var membershipIdParameter = membershipId.HasValue ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_MemberSchedule_Result>("CPF_MemberSchedule", periodIdParameter, divisionIdParameter, gradIdParameter, designationIdParameter, membershipIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_MonthlyContribution_Result> CPF_MonthlyContribution(Nullable<int> amountTypeId, Nullable<System.DateTime> startPeriod, Nullable<System.DateTime> endPeriod, Nullable<int> divisionId, Nullable<int> gradId, Nullable<int> designationId, string membershipId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var amountTypeIdParameter = amountTypeId.HasValue ?
                new ObjectParameter("AmountTypeId", amountTypeId) :
                new ObjectParameter("AmountTypeId", typeof(int));
    
            var startPeriodParameter = startPeriod.HasValue ?
                new ObjectParameter("StartPeriod", startPeriod) :
                new ObjectParameter("StartPeriod", typeof(System.DateTime));
    
            var endPeriodParameter = endPeriod.HasValue ?
                new ObjectParameter("EndPeriod", endPeriod) :
                new ObjectParameter("EndPeriod", typeof(System.DateTime));
    
            var divisionIdParameter = divisionId.HasValue ?
                new ObjectParameter("DivisionId", divisionId) :
                new ObjectParameter("DivisionId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var membershipIdParameter = membershipId != null ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_MonthlyContribution_Result>("CPF_MonthlyContribution", amountTypeIdParameter, startPeriodParameter, endPeriodParameter, divisionIdParameter, gradIdParameter, designationIdParameter, membershipIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_ProvidentFundSatementProvisioin_Result> CPF_ProvidentFundSatementProvisioin(Nullable<int> periodId, Nullable<int> divisionId, Nullable<int> gradId, Nullable<int> designationId, Nullable<int> membershipId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var divisionIdParameter = divisionId.HasValue ?
                new ObjectParameter("DivisionId", divisionId) :
                new ObjectParameter("DivisionId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var membershipIdParameter = membershipId.HasValue ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_ProvidentFundSatementProvisioin_Result>("CPF_ProvidentFundSatementProvisioin", periodIdParameter, divisionIdParameter, gradIdParameter, designationIdParameter, membershipIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_RptGenerateScheduleofInvestment_Result> CPF_RptGenerateScheduleofInvestment(string investmentTypeId, Nullable<System.DateTime> dtFrom, Nullable<System.DateTime> dtTo, Nullable<int> investmentID, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var investmentTypeIdParameter = investmentTypeId != null ?
                new ObjectParameter("InvestmentTypeId", investmentTypeId) :
                new ObjectParameter("InvestmentTypeId", typeof(string));
    
            var dtFromParameter = dtFrom.HasValue ?
                new ObjectParameter("dtFrom", dtFrom) :
                new ObjectParameter("dtFrom", typeof(System.DateTime));
    
            var dtToParameter = dtTo.HasValue ?
                new ObjectParameter("dtTo", dtTo) :
                new ObjectParameter("dtTo", typeof(System.DateTime));
    
            var investmentIDParameter = investmentID.HasValue ?
                new ObjectParameter("InvestmentID", investmentID) :
                new ObjectParameter("InvestmentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_RptGenerateScheduleofInvestment_Result>("CPF_RptGenerateScheduleofInvestment", investmentTypeIdParameter, dtFromParameter, dtToParameter, investmentIDParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_RptInvestmentAccrualReport(string investmentTypeId, string investmentID, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var investmentTypeIdParameter = investmentTypeId != null ?
                new ObjectParameter("InvestmentTypeId", investmentTypeId) :
                new ObjectParameter("InvestmentTypeId", typeof(string));
    
            var investmentIDParameter = investmentID != null ?
                new ObjectParameter("InvestmentID", investmentID) :
                new ObjectParameter("InvestmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_RptInvestmentAccrualReport", investmentTypeIdParameter, investmentIDParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_ScheduleOfAdvanceLoan(Nullable<int> periodId, Nullable<int> divisionId, Nullable<int> gradId, Nullable<int> designationId, Nullable<int> membershipId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var divisionIdParameter = divisionId.HasValue ?
                new ObjectParameter("DivisionId", divisionId) :
                new ObjectParameter("DivisionId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var membershipIdParameter = membershipId.HasValue ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_ScheduleOfAdvanceLoan", periodIdParameter, divisionIdParameter, gradIdParameter, designationIdParameter, membershipIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_TrialBalanceByLevel(string pFYear, Nullable<int> selectedLavel, Nullable<System.DateTime> balanceDate, Nullable<int> isInclude)
        {
            var pFYearParameter = pFYear != null ?
                new ObjectParameter("PFYear", pFYear) :
                new ObjectParameter("PFYear", typeof(string));
    
            var selectedLavelParameter = selectedLavel.HasValue ?
                new ObjectParameter("SelectedLavel", selectedLavel) :
                new ObjectParameter("SelectedLavel", typeof(int));
    
            var balanceDateParameter = balanceDate.HasValue ?
                new ObjectParameter("BalanceDate", balanceDate) :
                new ObjectParameter("BalanceDate", typeof(System.DateTime));
    
            var isIncludeParameter = isInclude.HasValue ?
                new ObjectParameter("IsInclude", isInclude) :
                new ObjectParameter("IsInclude", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_TrialBalanceByLevel", pFYearParameter, selectedLavelParameter, balanceDateParameter, isIncludeParameter);
        }
    
        public virtual int CPF_VoucherGenerate(Nullable<int> voucherTypeId, Nullable<int> voucherStatusId, Nullable<int> periodId, string voucherNumber, string startPeriod, string endPeriod, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var voucherTypeIdParameter = voucherTypeId.HasValue ?
                new ObjectParameter("VoucherTypeId", voucherTypeId) :
                new ObjectParameter("VoucherTypeId", typeof(int));
    
            var voucherStatusIdParameter = voucherStatusId.HasValue ?
                new ObjectParameter("VoucherStatusId", voucherStatusId) :
                new ObjectParameter("VoucherStatusId", typeof(int));
    
            var periodIdParameter = periodId.HasValue ?
                new ObjectParameter("PeriodId", periodId) :
                new ObjectParameter("PeriodId", typeof(int));
    
            var voucherNumberParameter = voucherNumber != null ?
                new ObjectParameter("VoucherNumber", voucherNumber) :
                new ObjectParameter("VoucherNumber", typeof(string));
    
            var startPeriodParameter = startPeriod != null ?
                new ObjectParameter("StartPeriod", startPeriod) :
                new ObjectParameter("StartPeriod", typeof(string));
    
            var endPeriodParameter = endPeriod != null ?
                new ObjectParameter("EndPeriod", endPeriod) :
                new ObjectParameter("EndPeriod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_VoucherGenerate", voucherTypeIdParameter, voucherStatusIdParameter, periodIdParameter, voucherNumberParameter, startPeriodParameter, endPeriodParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_VoucherGenerateDetail_Result> CPF_VoucherGenerateDetail(Nullable<int> voucherId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var voucherIdParameter = voucherId.HasValue ?
                new ObjectParameter("VoucherId", voucherId) :
                new ObjectParameter("VoucherId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_VoucherGenerateDetail_Result>("CPF_VoucherGenerateDetail", voucherIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CommonConfigGetResult> CommonConfigGet(string strDisplayName, Nullable<int> intID, string strName, string strSortBy, string strSortType, Nullable<int> startRowIndex, Nullable<int> maximumRows, ObjectParameter numTotalRows, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var strDisplayNameParameter = strDisplayName != null ?
                new ObjectParameter("strDisplayName", strDisplayName) :
                new ObjectParameter("strDisplayName", typeof(string));
    
            var intIDParameter = intID.HasValue ?
                new ObjectParameter("intID", intID) :
                new ObjectParameter("intID", typeof(int));
    
            var strNameParameter = strName != null ?
                new ObjectParameter("strName", strName) :
                new ObjectParameter("strName", typeof(string));
    
            var strSortByParameter = strSortBy != null ?
                new ObjectParameter("strSortBy", strSortBy) :
                new ObjectParameter("strSortBy", typeof(string));
    
            var strSortTypeParameter = strSortType != null ?
                new ObjectParameter("strSortType", strSortType) :
                new ObjectParameter("strSortType", typeof(string));
    
            var startRowIndexParameter = startRowIndex.HasValue ?
                new ObjectParameter("startRowIndex", startRowIndex) :
                new ObjectParameter("startRowIndex", typeof(int));
    
            var maximumRowsParameter = maximumRows.HasValue ?
                new ObjectParameter("maximumRows", maximumRows) :
                new ObjectParameter("maximumRows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CommonConfigGetResult>("CommonConfigGet", strDisplayNameParameter, intIDParameter, strNameParameter, strSortByParameter, strSortTypeParameter, startRowIndexParameter, maximumRowsParameter, numTotalRows, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_FinalResultOfCpf_EmployeeWise_Result> CPF_FinalResultOfCpf_EmployeeWise(Nullable<int> employeeId, Nullable<System.DateTime> toDate)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_FinalResultOfCpf_EmployeeWise_Result>("CPF_FinalResultOfCpf_EmployeeWise", employeeIdParameter, toDateParameter);
        }
    
        public virtual ObjectResult<CPF_GetContributionDuringtheYear_Result> CPF_GetContributionDuringtheYear(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> employeeId, Nullable<bool> isOwnContribution)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var isOwnContributionParameter = isOwnContribution.HasValue ?
                new ObjectParameter("IsOwnContribution", isOwnContribution) :
                new ObjectParameter("IsOwnContribution", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetContributionDuringtheYear_Result>("CPF_GetContributionDuringtheYear", startDateParameter, endDateParameter, employeeIdParameter, isOwnContributionParameter);
        }
    
        public virtual ObjectResult<CPF_RptCpfLoanInfo_Result> CPF_RptCpfLoanInfo(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_RptCpfLoanInfo_Result>("CPF_RptCpfLoanInfo", employeeIdParameter);
        }
    
        public virtual ObjectResult<CPF_RptMonthlyProvidentFundRegister_Result> CPF_RptMonthlyProvidentFundRegister(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_RptMonthlyProvidentFundRegister_Result>("CPF_RptMonthlyProvidentFundRegister", employeeIdParameter);
        }
    
        public virtual ObjectResult<CPF_RptProvidentFundLoanInstallment_Result> CPF_RptProvidentFundLoanInstallment(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_RptProvidentFundLoanInstallment_Result>("CPF_RptProvidentFundLoanInstallment", employeeIdParameter);
        }
    
        public virtual ObjectResult<CPF_RptProvidentFundWorksheet_Result> CPF_RptProvidentFundWorksheet(Nullable<int> pfPeriodId, string employeeId, Nullable<int> departmentId, Nullable<int> designationId)
        {
            var pfPeriodIdParameter = pfPeriodId.HasValue ?
                new ObjectParameter("PfPeriodId", pfPeriodId) :
                new ObjectParameter("PfPeriodId", typeof(int));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_RptProvidentFundWorksheet_Result>("CPF_RptProvidentFundWorksheet", pfPeriodIdParameter, employeeIdParameter, departmentIdParameter, designationIdParameter);
        }
    
        public virtual ObjectResult<CPF_GetMyLoanSummary_Result> CPF_GetMyLoanSummary(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetMyLoanSummary_Result>("CPF_GetMyLoanSummary", employeeIdParameter);
        }
    
        public virtual ObjectResult<CPF_SP_PFListOfLoan_Result> CPF_SP_PFListOfLoan(string salaryYear, string salaryMonth, Nullable<int> employeeId, Nullable<bool> isRefundable, Nullable<bool> loanStatus, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var salaryYearParameter = salaryYear != null ?
                new ObjectParameter("SalaryYear", salaryYear) :
                new ObjectParameter("SalaryYear", typeof(string));
    
            var salaryMonthParameter = salaryMonth != null ?
                new ObjectParameter("SalaryMonth", salaryMonth) :
                new ObjectParameter("SalaryMonth", typeof(string));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var isRefundableParameter = isRefundable.HasValue ?
                new ObjectParameter("IsRefundable", isRefundable) :
                new ObjectParameter("IsRefundable", typeof(bool));
    
            var loanStatusParameter = loanStatus.HasValue ?
                new ObjectParameter("LoanStatus", loanStatus) :
                new ObjectParameter("LoanStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_PFListOfLoan_Result>("CPF_SP_PFListOfLoan", salaryYearParameter, salaryMonthParameter, employeeIdParameter, isRefundableParameter, loanStatusParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_SP_RptMonthlyPFStatement_Result> CPF_SP_RptMonthlyPFStatement(string salaryYear, string salaryMonth, Nullable<int> pEmployeeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var salaryYearParameter = salaryYear != null ?
                new ObjectParameter("SalaryYear", salaryYear) :
                new ObjectParameter("SalaryYear", typeof(string));
    
            var salaryMonthParameter = salaryMonth != null ?
                new ObjectParameter("SalaryMonth", salaryMonth) :
                new ObjectParameter("SalaryMonth", typeof(string));
    
            var pEmployeeIdParameter = pEmployeeId.HasValue ?
                new ObjectParameter("pEmployeeId", pEmployeeId) :
                new ObjectParameter("pEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptMonthlyPFStatement_Result>("CPF_SP_RptMonthlyPFStatement", salaryYearParameter, salaryMonthParameter, pEmployeeIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_DeleteMembership(Nullable<int> applicationId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var applicationIdParameter = applicationId.HasValue ?
                new ObjectParameter("applicationId", applicationId) :
                new ObjectParameter("applicationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_DeleteMembership", applicationIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_uspVoucherPostingForProfit_Result> CPF_uspVoucherPostingForPFProfit(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_uspVoucherPostingForProfit_Result>("CPF_uspVoucherPostingForPFProfit", idParameter);
        }
    
        public virtual ObjectResult<CPF_uspVoucherPostingForProfit_Result> CPF_uspVoucherPostingForFinalSettlement(Nullable<int> membershipId)
        {
            var membershipIdParameter = membershipId.HasValue ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_uspVoucherPostingForProfit_Result>("CPF_uspVoucherPostingForFinalSettlement", membershipIdParameter);
        }
    
        public virtual ObjectResult<CPF_GetContributionOfPF_Result> CPF_GetContributionOfPF(Nullable<int> employeeId, Nullable<bool> isOwnContribution)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var isOwnContributionParameter = isOwnContribution.HasValue ?
                new ObjectParameter("IsOwnContribution", isOwnContribution) :
                new ObjectParameter("IsOwnContribution", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetContributionOfPF_Result>("CPF_GetContributionOfPF", employeeIdParameter, isOwnContributionParameter);
        }
    
        public virtual ObjectResult<CPF_GetMyCPFSummary_Result> CPF_GetMyCPFSummary(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetMyCPFSummary_Result>("CPF_GetMyCPFSummary", empIDParameter);
        }
    
        [DbFunction("ERP_BEPZACPFEntities", "CPF_FN_GetEmployeeTotalContribution")]
        public virtual IQueryable<CPF_FN_GetEmployeeTotalContribution_Result> CPF_FN_GetEmployeeTotalContribution(Nullable<int> employeeId, Nullable<int> salaryHeadId, Nullable<System.DateTime> dateUpto)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var salaryHeadIdParameter = salaryHeadId.HasValue ?
                new ObjectParameter("SalaryHeadId", salaryHeadId) :
                new ObjectParameter("SalaryHeadId", typeof(int));
    
            var dateUptoParameter = dateUpto.HasValue ?
                new ObjectParameter("DateUpto", dateUpto) :
                new ObjectParameter("DateUpto", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CPF_FN_GetEmployeeTotalContribution_Result>("[ERP_BEPZACPFEntities].[CPF_FN_GetEmployeeTotalContribution](@EmployeeId, @SalaryHeadId, @DateUpto)", employeeIdParameter, salaryHeadIdParameter, dateUptoParameter);
        }
    
        public virtual ObjectResult<CPF_GetMyCPFLoanApplication_Result> CPF_GetMyCPFLoanApplication(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_GetMyCPFLoanApplication_Result>("CPF_GetMyCPFLoanApplication", employeeIdParameter);
        }
    
        public virtual int CPF_procProfitDistribution(string periodYear, string periodMonth, Nullable<decimal> interestRate, string remarks, string strUser, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var periodYearParameter = periodYear != null ?
                new ObjectParameter("PeriodYear", periodYear) :
                new ObjectParameter("PeriodYear", typeof(string));
    
            var periodMonthParameter = periodMonth != null ?
                new ObjectParameter("PeriodMonth", periodMonth) :
                new ObjectParameter("PeriodMonth", typeof(string));
    
            var interestRateParameter = interestRate.HasValue ?
                new ObjectParameter("InterestRate", interestRate) :
                new ObjectParameter("InterestRate", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var strUserParameter = strUser != null ?
                new ObjectParameter("strUser", strUser) :
                new ObjectParameter("strUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_procProfitDistribution", periodYearParameter, periodMonthParameter, interestRateParameter, remarksParameter, strUserParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual int CPF_procProfitDistributionRollback(Nullable<int> periodDurationId, string strUser, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var periodDurationIdParameter = periodDurationId.HasValue ?
                new ObjectParameter("PeriodDurationId", periodDurationId) :
                new ObjectParameter("PeriodDurationId", typeof(int));
    
            var strUserParameter = strUser != null ?
                new ObjectParameter("strUser", strUser) :
                new ObjectParameter("strUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPF_procProfitDistributionRollback", periodDurationIdParameter, strUserParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_SP_RptMonthlyPFStatementMaster_Result> CPF_SP_RptMonthlyPFStatementMaster(string salaryYear, string salaryMonth, Nullable<int> pEmployeeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var salaryYearParameter = salaryYear != null ?
                new ObjectParameter("SalaryYear", salaryYear) :
                new ObjectParameter("SalaryYear", typeof(string));
    
            var salaryMonthParameter = salaryMonth != null ?
                new ObjectParameter("SalaryMonth", salaryMonth) :
                new ObjectParameter("SalaryMonth", typeof(string));
    
            var pEmployeeIdParameter = pEmployeeId.HasValue ?
                new ObjectParameter("pEmployeeId", pEmployeeId) :
                new ObjectParameter("pEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptMonthlyPFStatementMaster_Result>("CPF_SP_RptMonthlyPFStatementMaster", salaryYearParameter, salaryMonthParameter, pEmployeeIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_SP_RptIndividualMonthlyPFStatement_Result> CPF_SP_RptIndividualMonthlyPFStatement(string salaryYear, string salaryMonth, Nullable<int> pEmployeeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var salaryYearParameter = salaryYear != null ?
                new ObjectParameter("SalaryYear", salaryYear) :
                new ObjectParameter("SalaryYear", typeof(string));
    
            var salaryMonthParameter = salaryMonth != null ?
                new ObjectParameter("SalaryMonth", salaryMonth) :
                new ObjectParameter("SalaryMonth", typeof(string));
    
            var pEmployeeIdParameter = pEmployeeId.HasValue ?
                new ObjectParameter("pEmployeeId", pEmployeeId) :
                new ObjectParameter("pEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptIndividualMonthlyPFStatement_Result>("CPF_SP_RptIndividualMonthlyPFStatement", salaryYearParameter, salaryMonthParameter, pEmployeeIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_SP_RptNewJoinInMembership_Result> CPF_SP_RptNewJoinInMembership(string year, string month, Nullable<bool> isInactive)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var isInactiveParameter = isInactive.HasValue ?
                new ObjectParameter("IsInactive", isInactive) :
                new ObjectParameter("IsInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptNewJoinInMembership_Result>("CPF_SP_RptNewJoinInMembership", yearParameter, monthParameter, isInactiveParameter);
        }
    
        public virtual ObjectResult<CPF_SP_RptPFStatementHistory_Result> CPF_SP_RptPFStatementHistory(string salaryYear, string salaryMonth, Nullable<int> pEmployeeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var salaryYearParameter = salaryYear != null ?
                new ObjectParameter("SalaryYear", salaryYear) :
                new ObjectParameter("SalaryYear", typeof(string));
    
            var salaryMonthParameter = salaryMonth != null ?
                new ObjectParameter("SalaryMonth", salaryMonth) :
                new ObjectParameter("SalaryMonth", typeof(string));
    
            var pEmployeeIdParameter = pEmployeeId.HasValue ?
                new ObjectParameter("pEmployeeId", pEmployeeId) :
                new ObjectParameter("pEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptPFStatementHistory_Result>("CPF_SP_RptPFStatementHistory", salaryYearParameter, salaryMonthParameter, pEmployeeIdParameter, numErrorCode, strErrorMsg);
        }
    
        public virtual ObjectResult<CPF_SP_RptIndividualYearlyPFStatement_Result> CPF_SP_RptIndividualYearlyPFStatement(Nullable<int> pEmployeeId, Nullable<int> pFinancialYearId)
        {
            var pEmployeeIdParameter = pEmployeeId.HasValue ?
                new ObjectParameter("pEmployeeId", pEmployeeId) :
                new ObjectParameter("pEmployeeId", typeof(int));
    
            var pFinancialYearIdParameter = pFinancialYearId.HasValue ?
                new ObjectParameter("pFinancialYearId", pFinancialYearId) :
                new ObjectParameter("pFinancialYearId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptIndividualYearlyPFStatement_Result>("CPF_SP_RptIndividualYearlyPFStatement", pEmployeeIdParameter, pFinancialYearIdParameter);
        }
    
        public virtual ObjectResult<CPF_SP_RptYearlyPFStatement_Result> CPF_SP_RptYearlyPFStatement(Nullable<int> pFinancialYearId)
        {
            var pFinancialYearIdParameter = pFinancialYearId.HasValue ?
                new ObjectParameter("pFinancialYearId", pFinancialYearId) :
                new ObjectParameter("pFinancialYearId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptYearlyPFStatement_Result>("CPF_SP_RptYearlyPFStatement", pFinancialYearIdParameter);
        }
    
        public virtual ObjectResult<CPF_RptCpfMemberInformation_Result> CPF_RptCpfMemberInformation(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_RptCpfMemberInformation_Result>("CPF_RptCpfMemberInformation", employeeIdParameter);
        }
    
        public virtual ObjectResult<CPF_SP_RptNomineeFormInformation_Result> CPF_SP_RptNomineeFormInformation(Nullable<int> employeeId, ObjectParameter numErrorCode, ObjectParameter strErrorMsg)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CPF_SP_RptNomineeFormInformation_Result>("CPF_SP_RptNomineeFormInformation", employeeIdParameter, numErrorCode, strErrorMsg);
        }
    }
}
