//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.WFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_WelfareFundCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFM_WelfareFundCategory()
        {
            this.WFM_ApprovalWelfareFundInfo = new HashSet<WFM_ApprovalWelfareFundInfo>();
            this.WFM_OfflineApplicationInfo = new HashSet<WFM_OfflineApplicationInfo>();
            this.WFM_OnlineApplicationInfo = new HashSet<WFM_OnlineApplicationInfo>();
            this.WFM_ReasonOfWelfareCategory = new HashSet<WFM_ReasonOfWelfareCategory>();
            this.WFM_WelfareFundPolicy = new HashSet<WFM_WelfareFundPolicy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> COAId { get; set; }
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_ApprovalWelfareFundInfo> WFM_ApprovalWelfareFundInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_OfflineApplicationInfo> WFM_OfflineApplicationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_OnlineApplicationInfo> WFM_OnlineApplicationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_ReasonOfWelfareCategory> WFM_ReasonOfWelfareCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_WelfareFundPolicy> WFM_WelfareFundPolicy { get; set; }
    }
}
