//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.WFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_ApprovalWelfareFundInfoCommittee
    {
        public int Id { get; set; }
        public int ApprovalWelfareFundInfoId { get; set; }
        public bool IsExternal { get; set; }
        public Nullable<int> MemberEmployeeId { get; set; }
        public string MemberName { get; set; }
        public string MemberDesignation { get; set; }
        public string MemberRole { get; set; }
        public bool ActiveStatus { get; set; }
        public int SortOrder { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual WFM_ApprovalWelfareFundInfo WFM_ApprovalWelfareFundInfo { get; set; }
    }
}
