//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.WFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_VerifyTheApplicationDetails
    {
        public int Id { get; set; }
        public int VerifyTheApplicationId { get; set; }
        public int EmployeeId { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> AppliedAmount { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual WFM_VerifyTheApplication WFM_VerifyTheApplication { get; set; }
    }
}
