//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.WFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_VerifyTheApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFM_VerifyTheApplication()
        {
            this.WFM_VerifyTheApplicationDetails = new HashSet<WFM_VerifyTheApplicationDetails>();
        }
    
        public int Id { get; set; }
        public string ApplicationStatus { get; set; }
        public int ApplicantZoneInfoId { get; set; }
        public Nullable<int> CycleId { get; set; }
        public string Year { get; set; }
        public System.DateTime VerifyDate { get; set; }
        public int VerifiedById { get; set; }
        public string Comments { get; set; }
        public Nullable<int> WelfareFundCategoryId { get; set; }
        public int ZoneInfoId { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_VerifyTheApplicationDetails> WFM_VerifyTheApplicationDetails { get; set; }
    }
}
