//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.AMS
{
    using System;
    
    public partial class AMS_SP_RptEmployeeJobCard_Result1
    {
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string DayStatus { get; set; }
        public string Name { get; set; }
        public Nullable<int> DesigId { get; set; }
        public string Designation { get; set; }
        public Nullable<int> CatId { get; set; }
        public string Category { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string ShiftInTime { get; set; }
        public string ShiftOutTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string Office { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Department { get; set; }
        public Nullable<int> SecId { get; set; }
        public string Section { get; set; }
    }
}
