//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_AnsarPhoto
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public byte[] PhotoSignature { get; set; }
        public bool IsPhoto { get; set; }
    
        public virtual AMS_AnsarEmpInfo AMS_AnsarEmpInfo { get; set; }
    }
}
