//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_AnsarServiceHistory
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int ZoneId { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string RemarkableWork { get; set; }
        public string Comment { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string DisciplinaryRecord { get; set; }
    
        public virtual AMS_AnsarEmpInfo AMS_AnsarEmpInfo { get; set; }
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
    }
}
