//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_ZoneInfo
    {
        public PRM_ZoneInfo()
        {
            this.AMS_ZoneWiseQuota = new HashSet<AMS_ZoneWiseQuota>();
            this.AMS_AnsarEmpInfo = new HashSet<AMS_AnsarEmpInfo>();
            this.PRM_EmploymentInfo = new HashSet<PRM_EmploymentInfo>();
            this.SMS_SecurityInfo = new HashSet<SMS_SecurityInfo>();
            this.AMS_AnsarServiceHistory = new HashSet<AMS_AnsarServiceHistory>();
            this.SMS_SecurityServiceHistory = new HashSet<SMS_SecurityServiceHistory>();
        }
    
        public int Id { get; set; }
        public string ZoneName { get; set; }
        public string ZoneCode { get; set; }
        public int SortOrder { get; set; }
        public int OrganogramCategoryTypeId { get; set; }
        public string ZoneAddress { get; set; }
        public string Prefix { get; set; }
        public string ZoneNameInBengali { get; set; }
        public string ZoneAddressInBengali { get; set; }
        public bool IsHeadOffice { get; set; }
        public string ZoneCodeForBillingSystem { get; set; }
    
        public virtual ICollection<AMS_ZoneWiseQuota> AMS_ZoneWiseQuota { get; set; }
        public virtual ICollection<AMS_AnsarEmpInfo> AMS_AnsarEmpInfo { get; set; }
        public virtual ICollection<PRM_EmploymentInfo> PRM_EmploymentInfo { get; set; }
        public virtual ICollection<SMS_SecurityInfo> SMS_SecurityInfo { get; set; }
        public virtual ICollection<AMS_AnsarServiceHistory> AMS_AnsarServiceHistory { get; set; }
        public virtual ICollection<SMS_SecurityServiceHistory> SMS_SecurityServiceHistory { get; set; }
    }
}
