//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_SecurityServiceHistory
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int SecurityInfoId { get; set; }
        public int WorkZoneId { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string DisciplineRecord { get; set; }
        public string Remarks { get; set; }
        public bool Is_Intelligence { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Award { get; set; }
    
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
        public virtual SMS_SecurityInfo SMS_SecurityInfo { get; set; }
    }
}
