//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_SecurityInfo
    {
        public SMS_SecurityInfo()
        {
            this.SMS_SecurityServiceHistory = new HashSet<SMS_SecurityServiceHistory>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> DateofPromotion { get; set; }
        public int ZoneInfoId { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
    
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
        public virtual PRM_ZoneInfo PRM_ZoneInfo { get; set; }
        public virtual ICollection<SMS_SecurityServiceHistory> SMS_SecurityServiceHistory { get; set; }
    }
}
