//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeList
    {
        public string FullName { get; set; }
        public System.DateTime DateofJoining { get; set; }
        public Nullable<System.DateTime> DateofConfirmation { get; set; }
        public string EmpStatus { get; set; }
        public string Location { get; set; }
        public string Division { get; set; }
        public string EmpType { get; set; }
        public string EmployeeInitial { get; set; }
        public string EmpID { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateofInactive { get; set; }
        public int EmploymentStatusId { get; set; }
        public int JobLocationId { get; set; }
        public int DivisionId { get; set; }
        public int DesignationId { get; set; }
        public int GradeId { get; set; }
        public int EmploymentTypeId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> SeparationDate { get; set; }
        public string SeparationType { get; set; }
        public int ProvisionMonth { get; set; }
        public int StaffCategoryId { get; set; }
        public string StaffCategory { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<System.DateTime> ContractExpireDate { get; set; }
        public Nullable<System.DateTime> DateofRetirement { get; set; }
        public Nullable<System.DateTime> ContractExpireOrRetirementDate { get; set; }
    }
}
