//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    
    public partial class GetEmployeeServiceLength
    {
        public string EmpID { get; set; }
        public string EmployeeInitial { get; set; }
        public string Name { get; set; }
        public string Division { get; set; }
        public string Designation { get; set; }
        public string EmploymentType { get; set; }
        public double TotalServiceLength { get; set; }
        public Nullable<double> TotalLeave { get; set; }
    }
}
