//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    
    public partial class GetEmployeeDOB
    {
        public string EmpID { get; set; }
        public string EmployeeInitial { get; set; }
        public string FullName { get; set; }
        public string Division { get; set; }
        public string EmpType { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string EmpBloodGroup { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string StaffCategory { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
    }
}
