//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    
    public partial class GettingEmpForAnnualIncrement
    {
        public string EmpID { get; set; }
        public string EmployeeInitial { get; set; }
        public string FullName { get; set; }
        public string Designation { get; set; }
        public string Division { get; set; }
        public string EmploymentType { get; set; }
        public System.DateTime DateofJoining { get; set; }
        public string GradeName { get; set; }
        public int StepName { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<System.DateTime> LastIncrementDate { get; set; }
        public Nullable<System.DateTime> NextIncrementDate { get; set; }
    }
}
