//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_tblLeaveType
    {
        public int intLeaveTypeID { get; set; }
        public string strLeaveType { get; set; }
        public string strLeaveShortName { get; set; }
        public int intPriority { get; set; }
        public bool bitIsEncashable { get; set; }
        public bool bitIsEarnLeave { get; set; }
        public string strEntitlementType { get; set; }
        public Nullable<int> intEarnLeaveUnitForDays { get; set; }
        public string strEarnLeaveCalculationType { get; set; }
        public string strCompanyID { get; set; }
        public string strIUser { get; set; }
        public string strEUser { get; set; }
        public Nullable<System.DateTime> dtIDate { get; set; }
        public Nullable<System.DateTime> dtEDate { get; set; }
        public Nullable<bool> isServiceLifeType { get; set; }
        public Nullable<int> intLeaveYearTypeId { get; set; }
        public Nullable<int> intApprovalGroupId { get; set; }
    }
}
