//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpAttachmentFile
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int AttachmentTypeId { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string OriginalFileName { get; set; }
        public byte[] Attachment { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> Size { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_AttachmentType PRM_AttachmentType { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
