//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpTransferInfo
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TransferDate { get; set; }
        public int FromDivisionId { get; set; }
        public int ToDivisionId { get; set; }
        public int FromLocationId { get; set; }
        public int ToLocationId { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_Division PRM_Division { get; set; }
        public virtual PRM_Division PRM_Division1 { get; set; }
        public virtual PRM_JobLocation PRM_JobLocation { get; set; }
        public virtual PRM_JobLocation PRM_JobLocation1 { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
