//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpFamilyMemberInfo
    {
        public PRM_EmpFamilyMemberInfo()
        {
            this.PRM_EmpNomineeDetail = new HashSet<PRM_EmpNomineeDetail>();
            this.PRM_EmpVisaPassportInfo = new HashSet<PRM_EmpVisaPassportInfo>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int RelationId { get; set; }
        public bool isDependent { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> DegreeLevelId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string ContractNo { get; set; }
        public string FaxNo { get; set; }
        public string NationalID { get; set; }
        public string EmailAddress { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public bool isAddPhoto { get; set; }
        public byte[] Photo { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_BloodGroup PRM_BloodGroup { get; set; }
        public virtual PRM_DegreeLevel PRM_DegreeLevel { get; set; }
        public virtual PRM_MaritalStatus PRM_MaritalStatus { get; set; }
        public virtual PRM_Nationality PRM_Nationality { get; set; }
        public virtual ICollection<PRM_EmpNomineeDetail> PRM_EmpNomineeDetail { get; set; }
        public virtual ICollection<PRM_EmpVisaPassportInfo> PRM_EmpVisaPassportInfo { get; set; }
        public virtual PRM_NameTitle PRM_NameTitle { get; set; }
        public virtual PRM_Profession PRM_Profession { get; set; }
        public virtual PRM_Relation PRM_Relation { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
