//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_HumanResourceRateAssignDetail
    {
        public int Id { get; set; }
        public int HRRateAssignMasterId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<decimal> ActualRate { get; set; }
        public Nullable<decimal> BudgetRate { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int EmploymentTypeId { get; set; }
    
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
        public virtual PRM_HumanResourceRateAssignMaster PRM_HumanResourceRateAssignMaster { get; set; }
    }
}
