//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpSeperation
    {
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int ShortageDays { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public bool isAddAttachment { get; set; }
        public string FileName { get; set; }
        public byte[] Attachment { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int PreviousEmploymentStatusId { get; set; }
    
        public virtual PRM_EmploymentStatus PRM_EmploymentStatus { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
