//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpPersonalInfo
    {
        public int EmployeeId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string PlaceofBirth { get; set; }
        public int CountryofBirthId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public int NationalityId { get; set; }
        public string NationalID { get; set; }
        public int MaritalStatusId { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Hieght { get; set; }
        public string SSN { get; set; }
        public string TIN { get; set; }
        public string PresentAddress1 { get; set; }
        public string PresentAddress2 { get; set; }
        public int PresentCountryId { get; set; }
        public int PresentDistictId { get; set; }
        public Nullable<int> PresentThanaId { get; set; }
        public string PresentPostCode { get; set; }
        public string PresentPhone { get; set; }
        public string PresentPhoneExtention { get; set; }
        public string PermanentAddress1 { get; set; }
        public string PermanentAddress2 { get; set; }
        public int PermanentCountryId { get; set; }
        public int PermanentDistictId { get; set; }
        public Nullable<int> PermanentThanaId { get; set; }
        public string PermanentPostCode { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentPhoneExtention { get; set; }
        public string Specialization { get; set; }
        public string Extracurricular { get; set; }
        public string PhysicalFitness { get; set; }
        public string Habits { get; set; }
        public string EOBINo { get; set; }
        public Nullable<System.DateTime> EOBIRegDate { get; set; }
        public bool isSmoke { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Email { get; set; }
    
        public virtual PRM_BloodGroup PRM_BloodGroup { get; set; }
        public virtual PRM_Country PRM_Country { get; set; }
        public virtual PRM_Country PRM_Country1 { get; set; }
        public virtual PRM_Country PRM_Country2 { get; set; }
        public virtual PRM_District PRM_District { get; set; }
        public virtual PRM_District PRM_District1 { get; set; }
        public virtual PRM_MaritalStatus PRM_MaritalStatus { get; set; }
        public virtual PRM_Nationality PRM_Nationality { get; set; }
        public virtual PRM_Thana PRM_Thana { get; set; }
        public virtual PRM_Thana PRM_Thana1 { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
