//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmploymentInfo
    {
        public PRM_EmploymentInfo()
        {
            this.PRM_DivisionHeadMaping = new HashSet<PRM_DivisionHeadMaping>();
            this.PRM_EmpAttachmentFile = new HashSet<PRM_EmpAttachmentFile>();
            this.PRM_EmpCertification = new HashSet<PRM_EmpCertification>();
            this.PRM_EmpContractInfo = new HashSet<PRM_EmpContractInfo>();
            this.PRM_EmpDegree = new HashSet<PRM_EmpDegree>();
            this.PRM_EmpDesignationChangeInfo = new HashSet<PRM_EmpDesignationChangeInfo>();
            this.PRM_EmpExperience = new HashSet<PRM_EmpExperience>();
            this.PRM_EmpFamilyMemberInfo = new HashSet<PRM_EmpFamilyMemberInfo>();
            this.PRM_EmpJobSkill = new HashSet<PRM_EmpJobSkill>();
            this.PRM_EmpLanguageEfficiency = new HashSet<PRM_EmpLanguageEfficiency>();
            this.PRM_EmpLicenseInfo = new HashSet<PRM_EmpLicenseInfo>();
            this.PRM_EmpNominee = new HashSet<PRM_EmpNominee>();
            this.PRM_EmpPhoto = new HashSet<PRM_EmpPhoto>();
            this.PRM_EmpPublicationInfo = new HashSet<PRM_EmpPublicationInfo>();
            this.PRM_EmpReferanceGuarantor = new HashSet<PRM_EmpReferanceGuarantor>();
            this.PRM_EmpStatusChange = new HashSet<PRM_EmpStatusChange>();
            this.PRM_EmpTrainingInfo = new HashSet<PRM_EmpTrainingInfo>();
            this.PRM_EmpTransferInfo = new HashSet<PRM_EmpTransferInfo>();
            this.PRM_EmpVisaPassportInfo = new HashSet<PRM_EmpVisaPassportInfo>();
            this.PRM_HumanResourceRateAssignDetail = new HashSet<PRM_HumanResourceRateAssignDetail>();
            this.PRM_EmployeeActivationHistory = new HashSet<PRM_EmployeeActivationHistory>();
        }
    
        public int Id { get; set; }
        public string EmpID { get; set; }
        public string EmployeeInitial { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateofJoining { get; set; }
        public int ProvisionMonth { get; set; }
        public Nullable<System.DateTime> DateofConfirmation { get; set; }
        public System.DateTime DateofPosition { get; set; }
        public int DesignationId { get; set; }
        public int DivisionId { get; set; }
        public int JobLocationId { get; set; }
        public int DisciplineId { get; set; }
        public int ResourceLevelId { get; set; }
        public int StaffCategoryId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public int EmploymentTypeId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public bool IsContractual { get; set; }
        public bool IsConsultant { get; set; }
        public bool IsOvertimeEligible { get; set; }
        public Nullable<decimal> OvertimeRate { get; set; }
        public string MobileNo { get; set; }
        public string EmialAddress { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public string BankAccountNo { get; set; }
        public int EmploymentStatusId { get; set; }
        public Nullable<System.DateTime> DateofInactive { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<bool> IsBonusEligible { get; set; }
        public Nullable<bool> IsTaxPaidbyIWM { get; set; }
        public int JobGradeId { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> ContractExpireDate { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<decimal> ContractDuration { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<decimal> ActualRate { get; set; }
        public Nullable<decimal> BudgetRate { get; set; }
    
        public virtual PRM_BankBranch PRM_BankBranch { get; set; }
        public virtual PRM_BankName PRM_BankName { get; set; }
        public virtual PRM_Designation PRM_Designation { get; set; }
        public virtual PRM_Discipline PRM_Discipline { get; set; }
        public virtual PRM_Division PRM_Division { get; set; }
        public virtual ICollection<PRM_DivisionHeadMaping> PRM_DivisionHeadMaping { get; set; }
        public virtual ICollection<PRM_EmpAttachmentFile> PRM_EmpAttachmentFile { get; set; }
        public virtual ICollection<PRM_EmpCertification> PRM_EmpCertification { get; set; }
        public virtual ICollection<PRM_EmpContractInfo> PRM_EmpContractInfo { get; set; }
        public virtual PRM_EmpContractPersonInfo PRM_EmpContractPersonInfo { get; set; }
        public virtual ICollection<PRM_EmpDegree> PRM_EmpDegree { get; set; }
        public virtual ICollection<PRM_EmpDesignationChangeInfo> PRM_EmpDesignationChangeInfo { get; set; }
        public virtual ICollection<PRM_EmpExperience> PRM_EmpExperience { get; set; }
        public virtual ICollection<PRM_EmpFamilyMemberInfo> PRM_EmpFamilyMemberInfo { get; set; }
        public virtual ICollection<PRM_EmpJobSkill> PRM_EmpJobSkill { get; set; }
        public virtual ICollection<PRM_EmpLanguageEfficiency> PRM_EmpLanguageEfficiency { get; set; }
        public virtual ICollection<PRM_EmpLicenseInfo> PRM_EmpLicenseInfo { get; set; }
        public virtual PRM_EmploymentStatus PRM_EmploymentStatus { get; set; }
        public virtual PRM_EmploymentType PRM_EmploymentType { get; set; }
        public virtual PRM_JobLocation PRM_JobLocation { get; set; }
        public virtual PRM_NameTitle PRM_NameTitle { get; set; }
        public virtual PRM_ResourceLevel PRM_ResourceLevel { get; set; }
        public virtual PRM_ShiftName PRM_ShiftName { get; set; }
        public virtual PRM_StaffCategory PRM_StaffCategory { get; set; }
        public virtual ICollection<PRM_EmpNominee> PRM_EmpNominee { get; set; }
        public virtual PRM_EmpPersonalInfo PRM_EmpPersonalInfo { get; set; }
        public virtual ICollection<PRM_EmpPhoto> PRM_EmpPhoto { get; set; }
        public virtual ICollection<PRM_EmpPublicationInfo> PRM_EmpPublicationInfo { get; set; }
        public virtual ICollection<PRM_EmpReferanceGuarantor> PRM_EmpReferanceGuarantor { get; set; }
        public virtual PRM_EmpSalary PRM_EmpSalary { get; set; }
        public virtual PRM_EmpSeperation PRM_EmpSeperation { get; set; }
        public virtual ICollection<PRM_EmpStatusChange> PRM_EmpStatusChange { get; set; }
        public virtual ICollection<PRM_EmpTrainingInfo> PRM_EmpTrainingInfo { get; set; }
        public virtual ICollection<PRM_EmpTransferInfo> PRM_EmpTransferInfo { get; set; }
        public virtual ICollection<PRM_EmpVisaPassportInfo> PRM_EmpVisaPassportInfo { get; set; }
        public virtual PRM_JobGrade PRM_JobGrade { get; set; }
        public virtual ICollection<PRM_HumanResourceRateAssignDetail> PRM_HumanResourceRateAssignDetail { get; set; }
        public virtual ICollection<PRM_EmployeeActivationHistory> PRM_EmployeeActivationHistory { get; set; }
    }
}
