//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_District
    {
        public PRM_District()
        {
            this.PRM_Thana = new HashSet<PRM_Thana>();
            this.PRM_EmpPersonalInfo = new HashSet<PRM_EmpPersonalInfo>();
            this.PRM_EmpPersonalInfo1 = new HashSet<PRM_EmpPersonalInfo>();
        }
    
        public int Id { get; set; }
        public string DistrictName { get; set; }
        public int DivisionId { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_CountryDivision PRM_CountryDivision { get; set; }
        public virtual ICollection<PRM_Thana> PRM_Thana { get; set; }
        public virtual ICollection<PRM_EmpPersonalInfo> PRM_EmpPersonalInfo { get; set; }
        public virtual ICollection<PRM_EmpPersonalInfo> PRM_EmpPersonalInfo1 { get; set; }
    }
}
