//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpCertification
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int CertificationCatagoryId { get; set; }
        public string CertificationTitle { get; set; }
        public int CertificationInstituteId { get; set; }
        public int CountryId { get; set; }
        public int CertificationYear { get; set; }
        public string Result { get; set; }
        public string CertificationDetails { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_CertificationCategory PRM_CertificationCategory { get; set; }
        public virtual PRM_CertificationInstitute PRM_CertificationInstitute { get; set; }
        public virtual PRM_Country PRM_Country { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
