//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpTrainingInfo
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int TrainingAreaId { get; set; }
        public Nullable<int> TrainingToolId { get; set; }
        public string TrainingTitle { get; set; }
        public string OrganizedBy { get; set; }
        public int CountryId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string CourseDetail { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_Country PRM_Country { get; set; }
        public virtual PRM_TrainingArea PRM_TrainingArea { get; set; }
        public virtual PRM_TrainingTools PRM_TrainingTools { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
