//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EmpExperience
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Organization1 { get; set; }
        public string Designation { get; set; }
        public int EmploymentTypeId { get; set; }
        public int OrganizationTypeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Responsibility { get; set; }
        public string Achievement { get; set; }
        public bool isInternalExperience { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PRM_EmploymentType PRM_EmploymentType { get; set; }
        public virtual PRM_OrganizationType PRM_OrganizationType { get; set; }
        public virtual PRM_EmploymentInfo PRM_EmploymentInfo { get; set; }
    }
}
