//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_Country
    {
        public PRM_Country()
        {
            this.PRM_CountryDivision = new HashSet<PRM_CountryDivision>();
            this.PRM_EmpCertification = new HashSet<PRM_EmpCertification>();
            this.PRM_EmpDegree = new HashSet<PRM_EmpDegree>();
            this.PRM_EmpVisaPassportInfo = new HashSet<PRM_EmpVisaPassportInfo>();
            this.PRM_EmpLicenseInfo = new HashSet<PRM_EmpLicenseInfo>();
            this.PRM_EmpPublicationInfo = new HashSet<PRM_EmpPublicationInfo>();
            this.PRM_EmpPersonalInfo = new HashSet<PRM_EmpPersonalInfo>();
            this.PRM_EmpPersonalInfo1 = new HashSet<PRM_EmpPersonalInfo>();
            this.PRM_EmpPersonalInfo2 = new HashSet<PRM_EmpPersonalInfo>();
            this.PRM_EmpTrainingInfo = new HashSet<PRM_EmpTrainingInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public string Remarks { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual ICollection<PRM_CountryDivision> PRM_CountryDivision { get; set; }
        public virtual ICollection<PRM_EmpCertification> PRM_EmpCertification { get; set; }
        public virtual ICollection<PRM_EmpDegree> PRM_EmpDegree { get; set; }
        public virtual ICollection<PRM_EmpVisaPassportInfo> PRM_EmpVisaPassportInfo { get; set; }
        public virtual ICollection<PRM_EmpLicenseInfo> PRM_EmpLicenseInfo { get; set; }
        public virtual ICollection<PRM_EmpPublicationInfo> PRM_EmpPublicationInfo { get; set; }
        public virtual ICollection<PRM_EmpPersonalInfo> PRM_EmpPersonalInfo { get; set; }
        public virtual ICollection<PRM_EmpPersonalInfo> PRM_EmpPersonalInfo1 { get; set; }
        public virtual ICollection<PRM_EmpPersonalInfo> PRM_EmpPersonalInfo2 { get; set; }
        public virtual ICollection<PRM_EmpTrainingInfo> PRM_EmpTrainingInfo { get; set; }
    }
}
