//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_OrganogramLevel
    {
        public PRM_OrganogramLevel()
        {
            this.PRM_OrganogramLevel1 = new HashSet<PRM_OrganogramLevel>();
        }
    
        public int Id { get; set; }
        public int OrganogramTypeId { get; set; }
        public string LevelName { get; set; }
        public int ParentId { get; set; }
        public string Prefix { get; set; }
        public int Position { get; set; }
        public bool IsActive { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual ICollection<PRM_OrganogramLevel> PRM_OrganogramLevel1 { get; set; }
        public virtual PRM_OrganogramLevel PRM_OrganogramLevel2 { get; set; }
        public virtual PRM_OrganogramType PRM_OrganogramType { get; set; }
    }
}
