//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_GradeStep
    {
        public PRM_GradeStep()
        {
            this.PRM_EmpSalary = new HashSet<PRM_EmpSalary>();
            this.PRM_SalaryStructure = new HashSet<PRM_SalaryStructure>();
            this.PRM_EmpStatusChange = new HashSet<PRM_EmpStatusChange>();
            this.PRM_EmpStatusChange1 = new HashSet<PRM_EmpStatusChange>();
        }
    
        public int Id { get; set; }
        public int JobGradeId { get; set; }
        public int StepName { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual ICollection<PRM_EmpSalary> PRM_EmpSalary { get; set; }
        public virtual ICollection<PRM_SalaryStructure> PRM_SalaryStructure { get; set; }
        public virtual ICollection<PRM_EmpStatusChange> PRM_EmpStatusChange { get; set; }
        public virtual ICollection<PRM_EmpStatusChange> PRM_EmpStatusChange1 { get; set; }
        public virtual PRM_JobGrade PRM_JobGrade { get; set; }
    }
}
