//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_JobGrade
    {
        public PRM_JobGrade()
        {
            this.PRM_Designation = new HashSet<PRM_Designation>();
            this.PRM_EmploymentInfo = new HashSet<PRM_EmploymentInfo>();
            this.PRM_EmpSalary = new HashSet<PRM_EmpSalary>();
            this.PRM_EmpStatusChange = new HashSet<PRM_EmpStatusChange>();
            this.PRM_EmpStatusChange1 = new HashSet<PRM_EmpStatusChange>();
            this.PRM_GradeStep = new HashSet<PRM_GradeStep>();
            this.PRM_HumanResourceRateDetail = new HashSet<PRM_HumanResourceRateDetail>();
            this.PRM_JobVacancyDetails = new HashSet<PRM_JobVacancyDetails>();
            this.PRM_SalaryStructure = new HashSet<PRM_SalaryStructure>();
        }
    
        public int Id { get; set; }
        public int StaffCategoryId { get; set; }
        public string GradeName { get; set; }
        public int NumberOfSteps { get; set; }
        public decimal InitialBasic { get; set; }
        public decimal LastBasic { get; set; }
        public decimal YearlyIncrement { get; set; }
        public System.DateTime DateOfEffective { get; set; }
        public string GradeCode { get; set; }
        public Nullable<bool> IsConsolidated { get; set; }
        public string IUser { get; set; }
        public string EUser { get; set; }
        public System.DateTime IDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int ResourceLevelId { get; set; }
    
        public virtual ICollection<PRM_Designation> PRM_Designation { get; set; }
        public virtual ICollection<PRM_EmploymentInfo> PRM_EmploymentInfo { get; set; }
        public virtual ICollection<PRM_EmpSalary> PRM_EmpSalary { get; set; }
        public virtual ICollection<PRM_EmpStatusChange> PRM_EmpStatusChange { get; set; }
        public virtual ICollection<PRM_EmpStatusChange> PRM_EmpStatusChange1 { get; set; }
        public virtual ICollection<PRM_GradeStep> PRM_GradeStep { get; set; }
        public virtual ICollection<PRM_HumanResourceRateDetail> PRM_HumanResourceRateDetail { get; set; }
        public virtual PRM_StaffCategory PRM_StaffCategory { get; set; }
        public virtual ICollection<PRM_JobVacancyDetails> PRM_JobVacancyDetails { get; set; }
        public virtual ICollection<PRM_SalaryStructure> PRM_SalaryStructure { get; set; }
    }
}
