//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmpFamilyInfoRpt
    {
        public int EmployeeId { get; set; }
        public string FullName { get; set; }
        public string RelationName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Gender { get; set; }
        public string BloodGroupName { get; set; }
        public string ProfessionName { get; set; }
        public string DegreeName { get; set; }
    }
}
