//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployeeFutureAnnualIncrement
    {
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeInitial { get; set; }
        public string Name { get; set; }
        public string Division { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string FromJobTitle { get; set; }
        public string FromJobGrade { get; set; }
        public int FromStep { get; set; }
        public decimal FromBasicSalary { get; set; }
        public string ToJobTitle { get; set; }
        public string ToJobGrade { get; set; }
        public int ToStep { get; set; }
        public decimal ToBasicSalary { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    }
}
