//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmpExperienceRpt
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Designation { get; set; }
        public string Organization { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Responsibility { get; set; }
        public string ExpertiseArea { get; set; }
    }
}
