//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmpTrainingRpt
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string TrainingTitle { get; set; }
        public Nullable<int> Duration { get; set; }
        public string TrainingArea { get; set; }
        public string Institute { get; set; }
        public int CountryId { get; set; }
        public string CountryName { get; set; }
    }
}
