//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MPA.DAL.PRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPromotedEmployee
    {
        public int Id { get; set; }
        public string EmployeeInitial { get; set; }
        public string FullName { get; set; }
        public string Division { get; set; }
        public int DivisionId { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime PromotionDate { get; set; }
        public string FromJobTitle { get; set; }
        public int FromJobTitleId { get; set; }
        public string FromJobGrade { get; set; }
        public int FromJobGradeId { get; set; }
        public int FromStep { get; set; }
        public int FromStepId { get; set; }
        public decimal FromBasicSalary { get; set; }
        public string ToJobTitle { get; set; }
        public int ToJobTitleId { get; set; }
        public string ToJobGrade { get; set; }
        public int ToJobGradeId { get; set; }
        public int ToStepId { get; set; }
        public int ToStep { get; set; }
        public decimal ToBasicSalary { get; set; }
        public string EmployeeID { get; set; }
    }
}
