//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMI_BudgetDetailsYearlyCost
    {
        public int Id { get; set; }
        public int BudgetDetailsId { get; set; }
        public int FinancialYearId { get; set; }
        public int BudgetStatusId { get; set; }
        public decimal EstematedCost { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PMI_ProjectStatus PMI_ProjectStatus { get; set; }
        public virtual acc_Accounting_Period_Information acc_Accounting_Period_Information { get; set; }
        public virtual PMI_BudgetDetails PMI_BudgetDetails { get; set; }
    }
}
