//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMI_ProjectMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMI_ProjectMaster()
        {
            this.PMI_ProjectDetails = new HashSet<PMI_ProjectDetails>();
            this.PMI_ProjectTimeExtension = new HashSet<PMI_ProjectTimeExtension>();
            this.PMI_ProjectZone = new HashSet<PMI_ProjectZone>();
            this.PMI_TenderDetails = new HashSet<PMI_TenderDetails>();
        }
    
        public int Id { get; set; }
        public int APPDetailsId { get; set; }
        public int MinistryId { get; set; }
        public int AgencyId { get; set; }
        public System.DateTime BudgetApprovalDate { get; set; }
        public string NameOfWorks { get; set; }
        public string ProcuringEntryName { get; set; }
        public string ProcuringEntryCode { get; set; }
        public string InvitationRefNo { get; set; }
        public Nullable<int> ConstructionTypeId { get; set; }
        public Nullable<int> ConstructionCategoryId { get; set; }
        public string DevelopmentPartner { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<System.DateTime> AdministrativeApprovalDate { get; set; }
        public Nullable<System.DateTime> TenderEvalDate { get; set; }
        public Nullable<System.DateTime> TenderIssueDate { get; set; }
        public Nullable<System.DateTime> TenderPubDate { get; set; }
        public Nullable<System.DateTime> TenderLastSellingDate { get; set; }
        public Nullable<System.DateTime> TenderClosingDateTime { get; set; }
        public Nullable<System.DateTime> TenderOpeningDateTime { get; set; }
        public Nullable<System.DateTime> ContractSignDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> SiteHandoverDate { get; set; }
        public Nullable<int> TimeExtensionInDays { get; set; }
        public Nullable<System.DateTime> AwardIssueDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ProjectStatusId { get; set; }
        public string SellingTenderDescription { get; set; }
        public string ReceivingTenderDescription { get; set; }
        public string OpeningTenderDescription { get; set; }
        public string PreTenderMeetingPlace { get; set; }
        public string EligibilityOfTenderer { get; set; }
        public string BriefDescription { get; set; }
        public string BriefDescriptionOfRelated { get; set; }
        public string Services { get; set; }
        public string NameOfInvitingTender { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string ProcureAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string FaxNumber { get; set; }
        public string Notice { get; set; }
        public Nullable<System.DateTime> SecurityMoneyReefingDate { get; set; }
        public string LiquidatedDamage { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<System.DateTime> FinalPaymentDate { get; set; }
        public string FileName { get; set; }
        public byte[] DrawingAttachment { get; set; }
        public Nullable<System.DateTime> DrawingApprovalDate { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int APPMasterId { get; set; }
        public string ContractorName { get; set; }
        public Nullable<System.DateTime> DateOfIssuingNOA { get; set; }
        public Nullable<System.DateTime> DateOfPGSubmission { get; set; }
        public Nullable<System.DateTime> DateOfPGExpire { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public Nullable<decimal> PhysicalProgress { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovalStatusId { get; set; }
    
        public virtual PMI_Agency PMI_Agency { get; set; }
        public virtual PMI_ConstructionCategory PMI_ConstructionCategory { get; set; }
        public virtual PMI_ConstructionType PMI_ConstructionType { get; set; }
        public virtual PMI_Ministry PMI_Ministry { get; set; }
        public virtual PMI_PaymentStatus PMI_PaymentStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMI_ProjectDetails> PMI_ProjectDetails { get; set; }
        public virtual PMI_ProjectStatus PMI_ProjectStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMI_ProjectTimeExtension> PMI_ProjectTimeExtension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMI_ProjectZone> PMI_ProjectZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMI_TenderDetails> PMI_TenderDetails { get; set; }
    }
}
