//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMI_EstimationHeadDescription
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public int EstimationHeadId { get; set; }
        public string HeadDescription { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PMI_EstimationHead PMI_EstimationHead { get; set; }
        public virtual PMI_EstimationMaster PMI_EstimationMaster { get; set; }
    }
}
