//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMI_ProjectDetails
    {
        public int Id { get; set; }
        public int ProjectMasterId { get; set; }
        public int ProcurementTypeId { get; set; }
        public int ProcurementMethodId { get; set; }
        public int SourceOfFundId { get; set; }
        public int ApprovalAuthorityId { get; set; }
        public string PackageNo { get; set; }
        public string PackageName { get; set; }
        public string Unit { get; set; }
        public int Quantity { get; set; }
        public decimal EstimatedCost { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual PMI_ApprovalAuthority PMI_ApprovalAuthority { get; set; }
        public virtual PMI_ProcurementMethod PMI_ProcurementMethod { get; set; }
        public virtual PMI_ProcurementType PMI_ProcurementType { get; set; }
        public virtual PMI_SourceOfFund PMI_SourceOfFund { get; set; }
        public virtual PMI_ProjectMaster PMI_ProjectMaster { get; set; }
    }
}
