//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMI_BudgetDetailsYearlyBilled
    {
        public int Id { get; set; }
        public int BudgetDetailsId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<decimal> BilledAmount { get; set; }
    
        public virtual PMI_BudgetDetails PMI_BudgetDetails { get; set; }
    }
}
