//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMI_ProgressReportDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMI_ProgressReportDetails()
        {
            this.PMI_ProgressReportDetailsYearlyBilled = new HashSet<PMI_ProgressReportDetailsYearlyBilled>();
        }
    
        public int Id { get; set; }
        public int ProgressReportMasterId { get; set; }
        public string NameOfWorks { get; set; }
        public string NameOfContractor { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public Nullable<decimal> AcceptedAmount { get; set; }
        public Nullable<System.DateTime> DateOfNOA { get; set; }
        public Nullable<System.DateTime> ExpireDateOfBG { get; set; }
        public Nullable<System.DateTime> DateOfContractAgreement { get; set; }
        public Nullable<System.DateTime> DateOfSiteHandingOver { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public Nullable<decimal> CompletionTime { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
        public Nullable<decimal> TimeElapsed { get; set; }
        public Nullable<decimal> PhysicalProgress { get; set; }
        public Nullable<int> WrokStatusId { get; set; }
        public string Remarks { get; set; }
        public string SerialNo { get; set; }
    
        public virtual PMI_ProgressReportMaster PMI_ProgressReportMaster { get; set; }
        public virtual PMI_WorkStatus PMI_WorkStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMI_ProgressReportDetailsYearlyBilled> PMI_ProgressReportDetailsYearlyBilled { get; set; }
    }
}
