//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEPZA_MEDICAL.DAL.PMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPMIBudgetInfo
    {
        public int BudgetId { get; set; }
        public int BudgetDetailsId { get; set; }
        public int YearlyCostId { get; set; }
        public int FinancialYearId { get; set; }
        public string FinancialYearName { get; set; }
        public bool IsActiveFy { get; set; }
        public string NameOfWorks { get; set; }
        public int ProcurementTypeId { get; set; }
        public string ProcurementType { get; set; }
        public decimal BudgetAmount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal AprovedAmount { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public int BudgetStatusId { get; set; }
        public string BudgetStatusName { get; set; }
        public string BudgetType { get; set; }
        public int ZoneId { get; set; }
        public Nullable<int> ProjectForId { get; set; }
    }
}
