//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_BEPZA.DAL.SMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_SecurityInfo
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int WorkZoneId { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string DisciplineRecord { get; set; }
        public string Remarks { get; set; }
        public bool Is_Intelligence { get; set; }
        public string IUser { get; set; }
        public System.DateTime IDate { get; set; }
        public string EUser { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public int ZoneInfoId { get; set; }
    }
}
